name: Test Context

on: push

jobs:
  contexttest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        customer: [ecommerce, banking]
        environment: [integration, staging, prod]
    env:
      VERSION: latest
      REPO: localhost

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Matrix Values
        run: |
          echo "${{ matrix.customer }} ${{ matrix.environment }} $VERSION $REPO"
